import { defineEventHandler } from 'h3';
import { Product, Service, CatalogItem } from '../db/index.js';

// Copy your product data from store-data.ts
const productsData = [
  {
    id: "lat-5440",
    name: "Dell Latitude 5440",
    brand: "Dell",
    category: "Laptops",
    segment: "products",
    shortDescription: "Business laptop with Intel Core i5/i7, 16GB RAM, 512GB SSD, Windows 11 Pro",
    specs: ["Intel Core i5/i7", "16GB RAM", "512GB SSD", "Windows 11 Pro"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year ProSupport",
    keywords: ["business", "laptop", "dell", "latitude", "windows"],
  },
  {
    id: "tp-t14",
    name: "Lenovo ThinkPad T14",
    brand: "Lenovo",
    category: "Laptops",
    segment: "products",
    shortDescription: "Business laptop with Intel Core i5/i7, 16GB RAM, 512GB SSD, TPM 2.0",
    specs: ["Intel Core i5/i7", "16GB RAM", "512GB SSD", "TPM 2.0"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year on-site",
    keywords: ["business", "laptop", "lenovo", "thinkpad", "tpm"],
  },
  {
    id: "lat-7440",
    name: "Dell Latitude 7440",
    brand: "Dell",
    category: "Laptops",
    segment: "products",
    shortDescription: "Premium business laptop with Intel Core i7-1365U, 32GB RAM, 1TB NVMe SSD",
    specs: ["Intel Core i7-1365U", "32GB RAM", "1TB NVMe SSD", '14" FHD+ Display', "Wi-Fi 6E + Thunderbolt 4"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year ProSupport Plus",
    keywords: ["business", "premium", "laptop", "dell", "latitude"],
  },
  {
    id: "opti-7010-new",
    name: "Dell OptiPlex 7010",
    brand: "Dell",
    category: "Desktops",
    segment: "products",
    shortDescription: "Business desktop with Intel Core i7, 16GB RAM, 1TB SSD, Windows 11 Pro",
    specs: ["Intel Core i7", "16GB RAM", "1TB SSD", "Windows 11 Pro"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year on-site",
    keywords: ["desktop", "business", "dell", "optiplex", "windows"],
  },
  {
    id: "ts-p3",
    name: "Lenovo ThinkStation P3",
    brand: "Lenovo",
    category: "Workstations",
    segment: "products",
    shortDescription: "Professional workstation with Intel Xeon, 32GB RAM, 1TB SSD, NVIDIA Graphics",
    specs: ["Intel Xeon", "32GB RAM", "1TB SSD", "NVIDIA Graphics"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year on-site",
    keywords: ["workstation", "professional", "lenovo", "thinkstation", "xeon"],
  },
  {
    id: "prec-3660-new",
    name: "Dell Precision 3660",
    brand: "Dell",
    category: "Workstations",
    segment: "products",
    shortDescription: "High-performance workstation with Intel Core i9, 64GB RAM, 2TB NVMe SSD, NVIDIA RTX A2000",
    specs: ["Intel Core i9", "64GB RAM", "2TB NVMe SSD", "NVIDIA RTX A2000", "TPM 2.0 + ProSupport Ready"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year ProSupport Plus",
    keywords: ["workstation", "high-performance", "dell", "precision", "rtx"],
  },
  {
    id: "dell-u2723qe-new",
    name: 'Dell UltraSharp 27"',
    brand: "Dell",
    category: "Monitors",
    segment: "products",
    shortDescription: '27" IPS Panel, QHD Resolution, USB-C Docking, Height Adjustable',
    specs: ['27" IPS Panel', "QHD Resolution", "USB-C Docking", "Height Adjustable"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year exchange",
    keywords: ["monitor", "display", "dell", "ultrasharp", "4k"],
  },
  {
    id: "lenovo-p27h",
    name: "Lenovo ThinkVision P27h-30",
    brand: "Lenovo",
    category: "Monitors",
    segment: "products",
    shortDescription: '27" QHD IPS, USB-C 100W Power Delivery, 99% sRGB Color, Daisy Chain',
    specs: ['27" QHD IPS', "USB-C 100W Power Delivery", "99% sRGB Color", "Daisy Chain + Ergonomic Stand"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year warranty",
    keywords: ["monitor", "display", "lenovo", "thinkvision", "usb-c"],
  },
  {
    id: "dell-u3423we",
    name: 'Dell UltraSharp 34" Curved',
    brand: "Dell",
    category: "Monitors",
    segment: "products",
    shortDescription: '34" WQHD Curved Panel, USB-C Hub + RJ45, Built for Multi-screen Productivity',
    specs: ['34" WQHD Curved Panel', "USB-C Hub + RJ45", "Dual HDMI/DP Inputs", "Built for Multi-screen Productivity"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year exchange",
    keywords: ["monitor", "curved", "dell", "ultrasharp", "productivity"],
  },
  {
    id: "dell-ud22",
    name: "Dell Universal Dock UD22",
    brand: "Dell",
    category: "Docks",
    segment: "products",
    shortDescription: "Multi-port USB-C Dock, HDMI + DisplayPort Outputs, Gigabit Ethernet",
    specs: ["Multi-port USB-C Dock", "HDMI + DisplayPort Outputs", "Gigabit Ethernet + USB Expansion", "Office and Hybrid-Work Ready"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year warranty",
    keywords: ["dock", "docking station", "dell", "usb-c", "hybrid"],
  },
  {
    id: "lenovo-dock-gen2",
    name: "Lenovo ThinkPad USB-C Dock Gen 2",
    brand: "Lenovo",
    category: "Docks",
    segment: "products",
    shortDescription: "USB-C Single Cable Docking, Dual Display Support, Multiple USB + LAN Ports",
    specs: ["USB-C Single Cable Docking", "Dual Display Support", "Multiple USB + LAN Ports", "Designed for ThinkPad Ecosystems"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "3-year warranty",
    keywords: ["dock", "docking station", "lenovo", "thinkpad", "usb-c"],
  },
  {
    id: "dell-headset",
    name: "Dell Pro Stereo Headset",
    brand: "Dell",
    category: "Computer Accessories",
    segment: "products",
    shortDescription: "Wired over-ear stereo headset, Noise-reducing boom microphone",
    specs: ["Wired over-ear stereo headset", "Noise-reducing boom microphone", "3.5mm + USB adapter support", "Built for meetings and daily calls"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "1-year warranty",
    keywords: ["headset", "audio", "dell", "meetings", "calls"],
  },
  {
    id: "lenovo-combo",
    name: "Lenovo Professional Wireless Combo",
    brand: "Lenovo",
    category: "Input Devices",
    segment: "products",
    shortDescription: "Wireless Keyboard + Mouse Set, Compact Receiver Connectivity",
    specs: ["Wireless Keyboard + Mouse Set", "Compact Receiver Connectivity", "Quiet-Touch Keys and Precision Tracking", "Clean Desk Deployment Ready"],
    price: null,
    availability: "in-stock",
    quoteOnly: true,
    warranty: "1-year warranty",
    keywords: ["keyboard", "mouse", "wireless", "lenovo", "combo"],
  },
];

export default defineEventHandler(async () => {
  try {
    // Clear existing products
    await Product.deleteMany({});
    console.log('Cleared existing products');
    
    // Insert products
    await Product.insertMany(productsData);
    console.log(`✅ Inserted ${productsData.length} products`);
    
    return {
      success: true,
      message: 'Products seeded successfully',
      count: productsData.length,
    };
  } catch (error) {
    console.error('Seeding error:', error);
    return {
      success: false,
      error: 'Failed to seed products',
    };
  }
});