"""Reusable operational task templates shown in the Tasks workspace."""

TASK_CATALOG: dict[str, tuple[str, ...]] = {
    "Website Merge": (
        "Audit existing website content and integrations",
        "Map product and customer database fields",
        "Clean and deduplicate migration data",
        "Merge product catalogue data",
        "Merge customer and order history",
        "Implement merged website components",
        "Test the staging environment",
        "Validate payments, quotes and order workflows",
        "Complete security and performance checks",
        "Deploy the merged website",
    ),
    "Hardware Refurbishment": (
        "Register laptop batch and serial numbers",
        "Run hardware diagnostics",
        "Record faults and required parts",
        "Repair or replace faulty components",
        "Install hardware upgrades",
        "Install operating system and drivers",
        "Install and configure required software",
        "Complete technical quality checks",
        "Grade and clean refurbished device",
        "Add approved device to stock inventory",
        "Create refurbished product listing",
    ),
    "RFQ & Tender Administration": (
        "Sourcing relevant RFQs and tenders",
        "Monitoring tender/RFQ opportunities and closing dates",
        "Reviewing tender/RFQ requirements",
        "Compiling RFQ/tender submissions",
        "Collecting required company/supporting documents",
        "Compliance checks",
        "Quality/QA checks before submission",
        "Sourcing supplier pricing",
        "Communicating with suppliers",
        "Comparing supplier pricing",
        "Preparing pricing",
        "Final compilation of submissions",
        "Preparing submissions for management approval",
        "Submitting RFQs/tenders",
        "Recording submission/outcome",
        "Following up on tender outcomes",
    ),
    "Technical Services": (
        "Desktop repairs",
        "Laptop repairs",
        "Laptop refurbishment",
        "Hardware troubleshooting",
        "Hardware upgrades",
        "Software upgrades",
        "Operating system installations/upgrades",
        "Microsoft Office installations/configuration",
        "Software installations",
        "Device preparation and testing",
        "Technical quality checks",
        "Remote technical support using AnyDesk",
        "On-site technical support where required",
        "Client technical troubleshooting",
        "Technical follow-ups",
    ),
    "Marketing & Social Media": (
        "Creating marketing content",
        "Posting content across social media platforms",
        "Maintaining the social media content schedule",
        "Monitoring social media activity",
        "Monitoring advertisements across platforms",
        "Updating/maintaining advertising campaigns",
        "Responding/escalating relevant client enquiries",
        "Promoting products and services",
    ),
    "Makro / Online Product Sales": (
        "Creating product listings",
        "Updating product descriptions/specifications",
        "Updating product pricing",
        "Monitoring product stock availability",
        "Monitoring client orders",
        "Processing/following up on orders",
        "Identifying low/out-of-stock products",
        "Coordinating stock replenishment",
        "Following up on delivery/order issues",
    ),
    "General Administration / Employee Administration": (
        "Employee administration",
        "Maintaining employee information",
        "Employee onboarding/offboarding administration",
        "Managing employee accounts/access",
        "Attendance administration",
        "Leave administration",
        "General employee requests",
        "Maintaining required employee documentation",
        "General office administration",
    ),
    "Office & Kitchen Supplies": (
        "Stationery",
        "Paper",
        "Files/folders",
        "Dividers",
        "Printer supplies",
        "Pens and other office consumables",
        "Kitchen supplies",
        "Coffee/tea",
        "Sugar/milk",
        "Water",
        "Cleaning/office consumables",
    ),
    "Client Support / Website Requests": (
        "Technical support ticket",
        "Quote request",
        "RFQ request",
        "Product enquiry",
        "Purchase/order request",
    ),
    "General Operations": (
        "Assigning work",
        "Monitoring employee workloads",
        "Following up on overdue work",
        "Monitoring deadlines",
        "Coordinating projects",
        "Managing operational requests",
        "Escalating issues",
        "Tracking outstanding approvals",
        "General business coordination",
    ),
}


CATEGORY_DEPARTMENTS: dict[str, str] = {
    "Website Merge": "Software Development",
    "Hardware Refurbishment": "Technical",
    "RFQ & Tender Administration": "Operations",
    "Technical Services": "Technical",
    "Marketing & Social Media": "Marketing",
    "Makro / Online Product Sales": "Sales",
    "General Administration / Employee Administration": "Administration",
    "Office & Kitchen Supplies": "Administration",
    "Client Support / Website Requests": "Support",
    "General Operations": "Operations",
}
